### ISSUE TITLE
make error with gcc 5.4.0

### ISSUE THREAD

**Issue by ounie-os** [griddb/griddb#280]
Griddb source code version is 4.3.0 and my gcc is 5.4.0, x64 ubuntu 16.04.
Do as suggest:
$ ./bootstrap.sh
$ ./configure
$ make 
and then there is an error:
./../utility/util/type.h:833:43: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘util::NormalOStringStream’)
      UTIL_EXCEPTION_CREATE_MESSAGE_STREAM << message)).get()

**Comment by knonomura** [comment]
Thank you for your usage.

We have confirmed the operation on Ubuntu 18.04 (gcc 4.8.5).
Could you please build with GCC 4.8 or use DEB package ?

Quick start (Using source code):
https://github.com/griddb/griddb_nosql/blob/master/README.md
DEB package:
https://github.com/griddb/griddb_nosql/releases/tag/v4.3.0

**Comment by ounie-os** [comment]
ohayo :)
Indeed the code works well on gcc 4.8.5 and I have tested it. Is there a plan to update gcc version?

**Comment by knonomura** [comment]
Yes, the plan is in place but it's not our top priority at the moment, 
so I don't think it will updated in the near future.
